### ISSUE TITLE
App won't install

### ISSUE THREAD

**Issue by mmadigan9** [skidlamer/krunker_hero#4]
When I make the chrome app, it won't let me install it. It tries to download a file, fails, then Chrome gives an access denied popup. What am I doing wrong? I uploaded the whole .zip file. Any help is appreciated.

**Comment by skidlamer** [comment]
1. Go to chrome://extensions/ and check the box for Developer mode in the top right.
2. Return Here then press the green 'Clone or download' button choose Download ZIP.
3. Locate the ZIP file on your computer and unzip it.
4. Go back to the chrome://extensions/ page
5. Click the 'Load unpacked extension' button and select the unzipped folder this extension.
