### ISSUE TITLE
bro, this doesn't work after the 1.6.7 patch, even u say u updated it.

### ISSUE THREAD

**Issue by able-j** [skidlamer/krunker_hero#6]
it doesn't work in 1.6.7. It says "INVALID VERSION" then stops working.

**Comment by arthurauffray** [comment]
it's a trojan
pls, trust me!!!!
I made one no virus, 609+ views, hand-coded with 4K horizon and me dad for the latest update.
Direct video link: https://cutit.org/krunkerhackvid
My channel: https://cutit.org/GoBayMax
(wuz at 35 subs, posted this video, now 59 subs)
